/***********************************************************************************************//**
 *  CMake placeholder to implement unit tests with GoogleTest.
 *  @file       test.hpp.in
 *  @authors    Carles Araguz (CA), carles.araguz@upc.edu
 *  @date       2018-oct-02
 *  @version    0.1
 *  @copyright  This file is part of a project developed by Nano-Satellite and Payload Laboratory
 *              (NanoSat Lab) at Technical University of Catalonia - UPC BarcelonaTech.
 **************************************************************************************************/

/***************************************************************************************************
 * (!) This file has been automatically generated by CMake. DO NOT MODIFY!
 **************************************************************************************************/


#ifndef UNIT_TEST_PLACEHOLDER_HPP
#define UNIT_TEST_PLACEHOLDER_HPP

#include <gtest/gtest.h>

/* Tests to run */
#include "/home/marc/pae-local/autonomous/pae-autonomy/prot-3-gasv2/test/model/test_AgentMotion.hpp"
#include "/home/marc/pae-local/autonomous/pae-autonomy/prot-3-gasv2/test/model/test_PayoffFunctions.hpp"


#endif /* UNIT_TEST_PLACEHOLDER_HPP */
